class Dolphins  {
void swim () {
System.out.println( "I am swimming");
    } }
class Fishes extends Dolphins{
string color;
string size;
if (size==large && color==grey)
{System.out.println(“This is Shark and eats other fishes ”);
}
If else (size==small && color==orange)
{ System.out.println(“This is Clownfish and makes jokes ”);
}
else
{ System.out.println(“This is Dolphin ”);
}}
public class Solution {
    public static void main (String[] args) {
Fishes(size==small, color==orange);
    }
}
