
class parrot
{ 
void dog()
{System.out.println("Woof,woof");
} 
void cat()
{System.out.println("Meow,Meow");
}
void rooster()
{System.out.println("Cock-a-doodle-doo");
}}
public class solution
{
public static void main(String[]  args)
{
parrot p1=new parrot();
parrot p2=new parrot();
parrot p3 = new parrot();
p1.dog();
p2.cat();
p3.rooster();
}}

//if  we need to add one more parrot means then we can add one method and construct 

void Duck() or void  phone()
